### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by n-ambati** [Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-#1]
After training the model with the data, for detecting new images I executed people_detection_image.py but the script is throwing an error at this line.

boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))

**Comment by Samjith888** [comment]
Which version of opencv u are using? Can u try downgrade or upgrade opencv and try this code

**Comment by n-ambati** [comment]
Thanks for the help. The issue is with the output model. Resolved the issue
