### ISSUE TITLE
Tensorflow version mismatch 

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-#10]
README says that I need Tensorflow version < 2 but when I am starting trying, I get this error:
`Using TensorFlow backend.
You are using tensorflow version 1.15.0. The minimum required version is 2.3.0 (blacklisted: []).
`

How do I fix this?

**Comment by Samjith888** [comment]
This is because pip install. Please install the keras retinanet by using the latest readme.

**Comment by Samjith888** [comment]
This is because pip install. Please install the keras retinanet by using the latest readme.
