### ISSUE TITLE
cordinate

### ISSUE THREAD

**Issue by ghost** [Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-#11]
Hi @Samjith888  with your repo will it be possble to generate both ground truth and predicted bounding box cordinates?

**Comment by Samjith888** [comment]
You can get the bounding box coordinates from following line 

https://github.com/Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-/blob/master/people_detection_image.py#L44
