### ISSUE TITLE
Custom Retinanet Training with TF1.15

### ISSUE THREAD

**Issue by Solfeggietto2019** [Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-#12]
Is there a way I can download the github that used to use tensorflow version 1.15 instead of 2.3?

**Comment by Samjith888** [comment]
Sorry for the late response .  This repo support tf version < 2.x

![image](https://user-images.githubusercontent.com/39676803/119767592-bab99200-bed4-11eb-95b8-e5dad8381a15.png)

Example:

```
Python             3.6.1
Tesnorflow         1.14.0
keras              2.3.1
keras-retinanet    0.5.1
```
