### ISSUE TITLE
cannot save model

### ISSUE THREAD

**Issue by authas** [Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-#14]
when I run this command
`python keras_retinanet/bin/train.py --weights resnet50_coco_best_v2.1.0.h5 --steps 400 --epochs 20 --snapshot-path snapshots --tensorboard-dir tensorboard csv dataset/train.csv dataset/classes.csv --val-annotations dataset/test.csv`

after 1st epoch, got an error like this
`TypeError: Layer tf.nn.convolution was passed non-JSON-serializable arguments. Arguments had types: {'filters': <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>, 'strides': [<class 'int'>, <class 'int'>], 'padding': <class 'str'>, 'dilations': [<class 'int'>, <class 'int'>], 'data_format': <class 'str'>, 'name': <class 'str'>}. They cannot be serialized out when saving the model.`

please help

**Comment by Samjith888** [comment]
Which tf and keras retinanet versions are you using ?

**Comment by authas** [comment]
> Which tf and keras retinanet versions are you using ?

tf version 2.5.0
keras-retinanet version 0.4.1

**Comment by Samjith888** [comment]
Please  go through the readme

![image](https://user-images.githubusercontent.com/39676803/119766686-184cdf00-bed3-11eb-9ca8-63992148e4d9.png)

I succefully trained the model by using 
```
Python             3.6.1
Tesnorflow         1.14.0
keras              2.3.1
keras-retinanet    0.5.1
```
