### ISSUE TITLE
error on training

### ISSUE THREAD

**Issue by ghost** [Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-#2]
Hi @Samjith888  upto build_dataset.py its fine. but on training i got this error..

from ..utils.compute_overlap import compute_overlap
ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap'

**Comment by Samjith888** [comment]
Have to compile extension .Run the following command in the cloned repository 

> python setup.py build_ext --inplace

**Comment by ghost** [comment]
Hi @Samjith888  thanks for your help. Will it be possible to generate time taken to process an image while detecting ?. my dataset is for only 1 class

**Comment by Samjith888** [comment]
It will take time if you run in tensorflow-cpu

**Comment by ghost** [comment]
Hi @Samjith888  one last thing will it be possible to grnerate predicted box       co-odinates? so as to able mAP calculation

**Comment by Samjith888** [comment]
> Hi @Samjith888 one last thing will it be possible to grnerate predicted box co-odinates? 

 boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0
 By using above code , u will get the bbox coordinates values

**Comment by ghost** [comment]
Hi@Samjith888  detection only on image that was used for training... not able to detect on different image.. any  wrong?

**Comment by Samjith888** [comment]
> Hi@Samjith888 detection only on image that was used for training... not able to detect on different image.. any wrong?

Have you converted the model for inference  after training?

**Comment by ghost** [comment]
@Samjith888  yes converted and its called model.h5. i  followed your procedure in "convert model"
