### ISSUE TITLE
Real Time Object Detection

### ISSUE THREAD

**Issue by davidbcaro** [Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-#3]
Hi @Samjith888, thanks for the guide. Is there a sample code for object detection on real time? Thanks

**Comment by Samjith888** [comment]
You can use `cv2.VideoCapture(0)’ function to capture from webcam and then 
` model.predict_on_batch’  on the frames  by using the trained model

**Comment by rawat123** [comment]
hi @Samjith888 how we can use exported inference  model in java,

**Comment by Samjith888** [comment]
> hi @Samjith888 how we can use exported inference model in java,

Sorry, I didn’t worked in java with deep learning.

May be the following links will help you

https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/package-summary

https://towardsdatascience.com/deploying-keras-deep-learning-models-with-java-62d80464f34a

**Comment by Nimra01** [comment]
I have trained the model and converted it to inference model. Now I want to test it on webcam in real time, but I'm getting this error : NameError: name 'keras' is not defined. I have used this code for this purpose:

`import cv2
import numpy as np
from PIL import Image
from keras_retinanet import models

#Load the saved model
model = keras.models.load_model('cconverted_model.h5')
video = cv2.VideoCapture(0)

while True:
        _, frame = video.read()

        #Convert the captured frame into RGB
        im = Image.fromarray(frame, 'RGB')

        #Resizing into 128x128 because we trained the model with this image size.
        im = im.resize((128,128))
        img_array = np.array(im)

        #Our keras model used a 4D tensor, (images x height x width x channel)
        #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)

        #Calling the predict method on model to predict 'me' on the image
        prediction = int(model.predict(img_array)[0][0])

        #if prediction is 0, which means I am missing on the image, then show the frame in gray color.
        if prediction == 0:
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        cv2.imshow("Capturing", frame)
        key=cv2.waitKey(1)
        if key == ord('q'):
                break
video.release()
cv2.destroyAllWindows()`

**Comment by Samjith888** [comment]
@Nimra01 
Please import keras

`import  keras`

**Comment by Samjith888** [comment]
@Nimra01 
Please import keras

`import  keras`

**Comment by Nimra01** [comment]
I had tried to import keras before but it gave an error : "TypeError:
('Keyword argument not understood:', 'freeze')"

**Comment by Samjith888** [comment]
Add the following lines in ur code before loding the model 

custom_objects = retinanet.custom_objects.copy()
custom_objects.update(keras_resnet.custom_objects)

#Load model 
model = keras.models.load_model('/path/to/model.h5', custom_objects=custom_objects)

**Comment by Nimra01** [comment]
[image: image.png]
Thank you! I am getting an error "name 'retinanet' is not defined'. Kindly
check my code, I'm not sure whether it's correct or not.
