### ISSUE TITLE
Resource exhausted: OOM when allocating tensor with shape[1,94,167,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc #1284

### ISSUE THREAD

**Issue by KulunuGeeganage** [Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-#4]
@Samjith888 

How did you overcome with this problem ? I'm referring to this repo >> https://github.com/Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-

I'm using Anaconda environment with python 3.6.1 and tensorflow gpu 1.14.0
Graphic NVIDIA Geforce 920M and running keras-retinanet

I'm getting following issue while training my custom data. (note.txt file attached here with)

Could you please help me to train my data set according to above specifications.

Input command

"python keras_retinanet/bin/train.py --weights resnet50_coco_best_v2.1.0.h5 --steps 400 --epochs 20 --snapshot-path snapshots --tensorboard-dir tensorboard csv dataset/train.csv dataset/classes.cs"

Here is the error message >> 
[note.txt](https://github.com/Samjith888/Keras-retinanet-Training-on-custom-datasets-for-Object-Detection-/files/4245774/note.txt)

**Comment by Samjith888** [comment]
Try by reducing smaller batch size `'batch_size'`

**Comment by KulunuGeeganage** [comment]
@Samjith888 

In which file which line should I change batch size ? train.py ?

Is this the line ?

parser.add_argument('--batch-size',       help='Size of the batches.', default=1, type=int)

How can I change it and what are the values ? Default it is 1. Am I correct ? Can I change like 
default  = 2 or 32 like that ?

**Comment by Samjith888** [comment]
Which version of tensorflow , keras retinanet and cuda you are using ? And what is the image resolution?

**Comment by Samjith888** [comment]
Closing this issue  since no updates
